# Generated by Django 3.2.6 on 2021-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ImageField(upload_to='blogs'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_two',
            field=models.ImageField(upload_to='blogs'),
        ),
        migrations.AlterField(
            model_name='places',
            name='image_one',
            field=models.ImageField(upload_to='places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='image_two',
            field=models.ImageField(upload_to='places'),
        ),
    ]
