# Generated by Django 3.2.6 on 2021-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
